/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CAAFrikFrak;

import javax.swing.JOptionPane;

/**
 *
 * @author Kleidmilson Alves
 */
public class FrikaFrak extends javax.swing.JFrame {
 int volta= 2;
    int botaoUsado [] = {0,0,0,0,0,0,0,0,0};
    int pXganho[] = {0,0,0,0,0,0,0,0,0};
    int pOganho[] = {0,0,0,0,0,0,0,0,0};
    
    int origem = -1; 
    int posicao = 0;
    
     int contadorX = 0;
     int contadorO = 0;
     
    boolean colocando = true;
int origemSelecionada = -1;

    
   
    
   int pXganho(){
   
   if(pXganho[0]==1 && pXganho[1]==1 && pXganho[2]==1){
   
   return 1;
   }
   
   if(pXganho[3]==1 && pXganho[4]==1 && pXganho[5]==1){
   
   return 1;
   }
   
   if(pXganho[6]==1 && pXganho[7]==1 && pXganho[8]==1){
   
   return 1;
   }
   
  if(pXganho[0]==1 && pXganho[3]==1 && pXganho[6]==1){
   
   return 1;
   }
  
  if(pXganho[1]==1 && pXganho[4]==1 && pXganho[7]==1){
   
   return 1;
   }
  
  if(pXganho[2]==1 && pXganho[5]==1 && pXganho[8]==1){
   
   return 1;
   }
  
  if(pXganho[2]==1 && pXganho[5]==1 && pXganho[8]==1){
   
   return 1;
   }
  if(pXganho[2]==1 && pXganho[4]==1 && pXganho[6]==1){
   
   return 1;
   }
  if(pXganho[0]==1 && pXganho[4]==1 && pXganho[8]==1){
   
   return 1;
   }
        return 0;
   }
   
   
   
   int pOganho(){
   
   if(pOganho[0]==1 && pOganho[1]==1 && pOganho[2]==1){
   
   return 1;
   }
   
   if(pOganho[3]==1 && pOganho[4]==1 && pOganho[5]==1){
   
   return 1;
   }
   
   if(pOganho[6]==1 && pOganho[7]==1 && pOganho[8]==1){
   
   return 1;
   }
   
  if(pOganho[0]==1 && pOganho[3]==1 && pOganho[6]==1){
   
   return 1;
   }
  
  if(pOganho[1]==1 && pOganho[4]==1 && pOganho[7]==1){
   
   return 1;
   }
  
  if(pOganho[2]==1 && pOganho[5]==1 && pOganho[8]==1){
   
   return 1;
   }
  
  if(pOganho[2]==1 && pOganho[5]==1 && pOganho[8]==1){
   
   return 1;
   }
  if(pOganho[2]==1 && pOganho[4]==1 && pOganho[6]==1){
   
   return 1;
   }
  if(pOganho[0]==1 && pOganho[4]==1 && pOganho[8]==1){
   
   return 1;
   }
        return 0;
   }
   
    /**
     * Creates new form FrikaFrak
     */
    public FrikaFrak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(51, 153, 255));
        reset.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        reset.setText("Reiniciar");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
   
        
        if (botaoUsado[0]==0){
        
        if (volta % 2 == 0 ){
        
        volta++;
        contadorX++;
        b0.setText("X");
         botaoUsado [0]=1;
         pXganho[0]=1;
         
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1 && result1 < 3){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;
 
contadorX++;


}
   else if(result2==1 && result2 < 3){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
    
   
   } 
       
    }          
       else {
                       
        volta++;
        b0.setText("O");
        botaoUsado [0]=1;
        pOganho[0]=1;
        contadorO++;
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1 ){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   } 
      
   
       
        }  }
         
    
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
   
          if (botaoUsado[1]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b1.setText("X");
         botaoUsado [1]=1;
         pXganho[1]=1;
         contadorX++;
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   } 
       
    }          
       else {
            
            
         volta++;
         b1.setText("O");
            botaoUsado [1]=1;
             pOganho[1]=1;
                 contadorO++;
                 
         int result1=pXganho();
         int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
     
          if (botaoUsado[2]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b2.setText("X");
         botaoUsado [2]=1;
         pXganho[2]=1;
         contadorX++;
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
  
       
    }          
       else {
                        
        volta++;
        b2.setText("O");
        botaoUsado [2]=1;
        pOganho[2]=1;
        contadorO++;
        int result1=pXganho();
   int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
   
   
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
           
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

          if (botaoUsado[3]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b3.setText("X");
         botaoUsado [3]=1;
         pXganho[3]=1;
         contadorX++;
         
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   } 
       
    }          
       else {
            
            
        volta++;
        b3.setText("O");
        botaoUsado [3]=1;
        pOganho[3]=1;
        contadorO++;
        
        int result1=pXganho();
        int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
   

        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
            
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
  
        if (botaoUsado[4]==0){
        
        if (volta % 2 == 0){
        
        volta++;
                b4.setText("X");
                botaoUsado [4]=1;
                 pXganho[4]=1;
                    contadorX++;
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
  
       
    }          
       else {
            
            
        volta++;
        b4.setText("O");
        botaoUsado [4]=1;
        pOganho[4]=1;
        contadorO++;
        
                 int result1=pXganho();
                 int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
    
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
     
        if (botaoUsado[5]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b5.setText("X");
         botaoUsado [5]=1;
         pXganho[5]=1;
         contadorX++;
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   }
    
       
    }          
       else {
            
            
        volta++;
        b5.setText("O");
        botaoUsado [5]=1;
        pOganho[5]=1;
        contadorO++;
        int result1=pXganho();
   int result2=pOganho();
   
   if (result1==1){

    JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
   
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
        
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed

        if (botaoUsado[6]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b6.setText("X");
         botaoUsado [6]=1;
         pXganho[6]=1;
         
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
       
    }          
       else {
            
            
        volta++;
        b6.setText("O");
        botaoUsado [6]=1;
        pOganho[6]=1;
        
        int result1=pXganho();
   int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
   
        if (botaoUsado[7]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b7.setText("X");
         botaoUsado [7]=1;
         pXganho[7]=1;
         
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
       
    }          
       else {
            
            
        volta++;
        b7.setText("O");
        botaoUsado [7]=1;
        pOganho[7]=1;
        
        int result1=pXganho();
   int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed

        if (botaoUsado[8]==0){
        
        if (volta % 2 == 0){
        
        volta++;
        b8.setText("X");
         botaoUsado [8]=1;
         pXganho[8]=1;
         
            int result1=pXganho();
            int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
       
    }          
       else {
            
            
        volta++;
        b8.setText("O");
        botaoUsado [8]=1;
        pOganho[8]=1;
        
        int result1=pXganho();
   int result2=pOganho();
   
   if (result1==1){

 JOptionPane.showMessageDialog(rootPane, "Jogador1 Ganhou! ") ;

}
   else if(result2==1){
   
    JOptionPane.showMessageDialog(rootPane, "Jogador2 Ganhou! ") ;
   
   
   }
        }
        }
        else {
        JOptionPane.showMessageDialog(rootPane, "Botao Usado!") ;
        
        }  
        
        
        
        
        
    }//GEN-LAST:event_b8ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
  
        
        volta = 2;
        for (int i=0; i < 9;i++){
        
        botaoUsado [i]=0;
        
        }
        
        for (int i=0; i < 9;i++){
        
        pXganho [i]=0;
        
        }
        
        for (int i=0; i < 9;i++){
        
        pOganho [i]=0;
        
        }
        
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrikaFrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrikaFrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrikaFrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrikaFrak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrikaFrak().setVisible(true);
              new  FrikaFrak().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
